language: python
python:
  - 3.8 
  - 3.9
before_install:
  - pip3 install -r requirements.txt
script:
  - python3 runtest.py
after_success:
  - bash <(curl -s https://codecov.io/bash)
notifications:
  email: false
