name: Workflow for Codecov
on: [push]

jobs:
  run:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest] # macos-latest, windows-latest
    env:
      OS: ${{ matrix.os }}
      PYTHON: '3.9'
    steps:
    - uses: actions/checkout@master
    - name: Setup Python
      uses: actions/setup-python@master
      with:
        python-version: 3.9
    - name: Generate coverage report
      run: |
        pip install -r requirements.txt
        pip install pytest-cov
        pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cpu
        pip install -U jax
        python3 setup.py build_ext --inplace
        pytest unittests.py --cov=pychop
        coverage xml
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v2
